providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["cd backend && npm install && npx prisma generate"]

[start]
cmd = "cd backend && npx prisma db push --accept-data-loss && node src/server.js"
