[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd backend && node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
